development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url:  redis://redistogo:a327f9cb673f822f0b2ae7da70c36404@hammerjaw.redistogo.com:10176/
  channel_prefix: trio_production
